import { Footer, Navbar } from "@/components/common";
import "./globals.css";
import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import { ThemeProvider } from "./theme-provider";
import Provider from "@/redux/provider";

const overpass = Overpass({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${overpass.className} bg-gray-100 dark:bg-darkBg`}>
        <Provider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
